name: deploy-storybook

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: install yarn
      run: npm install -g yarn
    - name: load dependencies
      run: yarn install
    - name: build storybook
      run: yarn build-storybook
