name: deploy-all

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: install yarn
      run: npm install -g yarn
    - name: load dependencies
      run: yarn install
    - name: build engine
      run: yarn build
      env:
        PUBLIC_URL: https://team-stargarden.github.io/crosstoria-frontend/ 
    - name: build storybook
      run: yarn build-storybook
    - name: cleanup
      run: |
        rm -r public
        mkdir public
    - name: move react build for deployment
      run: |
        mv build/* public/
        cp -r public/static/* public/
    - name: move storybook for deployment
      run: mv storybook-static public/storybook
    - name: GitHub Pages Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: public
        keep_history: true 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
